github.com:
    user: nicholasrq
    oauth_token: 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
    git_protocol: ssh
    users:
        nicholasrq:
            oauth_token: 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
