git:
  paging:
    colorArg: always
    useConfig: false
    pager: delta --dark --paging=never
customCommands:
  - key: '<c-q>'
    context: 'localBranches'
    command: 'nvim -c ":Octo pr create"'
    description: "Open new PR with Octo"

